#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="icoDyMSimpleFoam"

runApplication blockMesh
cp boundary constant/polyMesh
runApplication setSet -batch setBatch.setSet
runApplication setsToZones -noFlipMap
runApplication $application
